INSERT INTO produtos (nome, preco, descricao) VALUES
('Tênis de Corrida', 99.99, 'Tênis leve e amortecido para corridas'),
('Bola de Futebol', 29.99, 'Bola oficial para jogos de futebol'),
('Raquete de Tênis', 59.99, 'Raquete profissional para jogadores de tênis'),
('Luvas de Boxe', 49.99, 'Luvas para treinamento de boxe'),
('Bicicleta de Montanha', 349.99, 'Bicicleta resistente para trilhas e montanhas'),
('Corda de Pular', 9.99, 'Corda leve e ajustável para exercícios aeróbicos'),
('Camiseta Térmica para Corrida', 19.99, 'Camiseta que absorve o suor para corridas'),
('Bola de Basquete', 34.99, 'Bola de basquete de alta qualidade'),
('Óculos de Natação', 14.99, 'Óculos com vedação para natação'),
('Prancha de Surfe', 199.99, 'Prancha para surfistas iniciantes e intermediários'),
('Caneleira para Futebol', 24.99, 'Caneleira de proteção para jogadores de futebol'),
('Mochila de Hidratação', 39.99, 'Mochila com reservatório de água para atividades físicas'),
('Skate Completo', 79.99, 'Skate pronto para manobras e passeios'),
('Cronômetro Digital', 12.99, 'Cronômetro preciso para medição de tempo em treinos'),
('Patins Inline', 89.99, 'Patins ajustáveis para diversão e exercícios');
